### ISSUE TITLE
New export type broke lots of apps

### ISSUE THREAD

**Issue by smddzcy** [scttcper/tinycolor#208]
Hi there,

Your 3.3.0 update just broke all of our apps. We're using `@ant-design/colors`, which uses tinycolor, and the 3.3.0 ES module exports broke our apps with this error:

```
import { tinycolor } from './index';
^^^^^^
Cannot use import statement outside a module
```

It might be an issue with `@ant-design/colors` as well, but I don't think 3.3.0 is backward-compatible with 3.2.1. It's always better to respect semver and not make **breaking changes** on minor version updates 🤞

**Comment by pgsteven** [comment]
same issue, revert 3.3.0 please!

**Comment by smddzcy** [comment]
@scttcper Thanks a lot for the hotfix

**Comment by scttcper** [comment]
why is everything backwards in ant design world everyone seems to be using absolute garbage webpack configs

**Comment by xXAvoraXx** [comment]
same issue 3.3.1

**Comment by steezeburger** [comment]
I'm also having this issue, but my yarn.lock shows the latest for ant-design-color, which is using the proper version of tinycolor. Did something else happen recently to start causing this issue again?

**Comment by scttcper** [comment]
@steezeburger i think its ant-design-color this time, I would use 5.0.0 instead. 5.1.0 changed something with imports that was then reverted without a patch version yet. https://github.com/ant-design/ant-design-colors/releases/tag/v5.1.0

unreleased revert commit - https://github.com/ant-design/ant-design-colors/pull/75

**Comment by steezeburger** [comment]
@scttcper thanks for the quick reply! 

I will try to use 5.0.0. Unfortunately I am not using ant-design-colors directly. I am using antd, which requires ant-design-colors, which requires your library. antd's package.json specifies ^5.0.0 for ant-design-colors, so it installs 5.1.0. I am not a front end guy, is it possible to define sub dependency versions so I can explicitly install 5.0.1?

I of course could fork antd, but I do not want to begin maintaining that fork.

**Comment by scttcper** [comment]
@steezeburger since it sounds like you're using yarn you can use resolutions https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

Adding a resolution to your package.json and then running `yarn install` should fix it until they release a new version.
```json
{
  "resolutions": {
    "@ant-design/colors": "5.0.0",
  }
}
```

You might also be able to add `@ant-design/colors` to your dependencies pinned to "5.0.0" and get that specific version instead of 5.1.0
