### ISSUE TITLE
Running error on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by nevestuan** [scttcper/tinycolor#218]
The latest version 3.4.0 cause a deployment error on our AWS Elastic Beanstalk server. It makes server unable to start. Error Log:

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24) /var/app/current/node_modules/@ctrl/tinycolor/dist/module/conversion.js:1 import { bound01, pad2 } from './util'; ^^^^^^ SyntaxError: Cannot use import statement outside a module at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.<anonymous> (/var/app/current/node_modules/@ant-design/colors/dist/index.js:5:18) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) /var/app/current/node_modules/@ctrl/tinycolor/dist/module/conversion.js:1

**Comment by scttcper** [comment]
https://github.com/scttcper/tinycolor/issues/208#issuecomment-776243480
