### ISSUE TITLE
3.4.0: Cannot use import statement outside a module on version 

### ISSUE THREAD

**Issue by mmahalwy** [scttcper/tinycolor#219]
![image](https://user-images.githubusercontent.com/3749095/107443813-596cdf00-6aee-11eb-83ce-e6dec4fcddf0.png)

**Comment by scttcper** [comment]
https://github.com/scttcper/tinycolor/issues/208#issuecomment-776243480

**Comment by mmahalwy** [comment]
wow thanks for the quick reply!
