### ISSUE TITLE
Add file extensions to imports in module directory

### ISSUE THREAD

**Issue by jogibear9988** [scttcper/tinycolor#239]
Hello, 
I try to use your library direct from browser via import map, but it would not work cause your imports in lack the ".js" extension.

Would it be possible to add them?

**Comment by scttcper** [comment]
maybe just try the umd via unpkg https://www.unpkg.com/@ctrl/tinycolor@3.6.0/dist/bundles/tinycolor.umd.min.js

**Comment by jogibear9988** [comment]
I know that this works, but I work also on a UI Adapter for ioBroker, wich installs NPM Packages directly and loads them via importmaps, there I can not use unpkg.
And I do not use tinycolor directly, it's a dependency of another package.

**Comment by jogibear9988** [comment]
To fix jest error: https://stackoverflow.com/questions/73735202/typescript-jest-imports-with-js-extension-cause-error-cannot-find-module

**Comment by jogibear9988** [comment]
I added the fix to the pull req
