### ISSUE TITLE
v4: warning when installed with yarn

### ISSUE THREAD

**Issue by AviVahl** [scttcper/tinycolor#244]
We've just upgraded to `@ctrl/tinycolor@4.0.1` and yarn started giving: `warning Workspaces can only be enabled in private projects.`

Looking into the package.json of the new release, it is marked like a monorepo:
```json
{
...
  "workspaces": [
    "demo"
  ],
...
}
```

**Comment by scttcper** [comment]
eh leaning towards wontfix

**Comment by AviVahl** [comment]
I'd hate to fork the package just to get the warning fixed, but it is used in a project with over 2000 dependencies and is the only warning during `yarn`. :worried: Can I assist?

**Comment by AviVahl** [comment]
❤️
