### ISSUE TITLE
[Bug] Next.js 14.0.4 every operation on TinyColor returns black #000000

### ISSUE THREAD

**Issue by Specy** [scttcper/tinycolor#248]
When doing a production build of next.js 14.0.4 (does not happen in 14.0.3 and below) whenever i construct a TinyColor, it is always considered as pure black. During the development build everything seems to work, but in production build it breaks.

I made an example on code sandbox with this issue [here](https://codesandbox.io/p/devbox/practical-pasteur-cl25r6?file=%2Fapp%2Fpage.tsx%3A7%2C53&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrgqbw6s0007356gikpotuj7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrgqbw6r0002356gj4ork5bt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrgqbw6r0004356g8twxvc3w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrgqbw6r0006356gxympnsru%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrgqbw6r0002356gj4ork5bt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrgqbw6r0001356go56xvire%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrgqrxuw0002356g8qywfw6y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A53%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A53%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrgqbw6r0002356gj4ork5bt%2522%252C%2522activeTabId%2522%253A%2522clrgqrxuw0002356g8qywfw6y%2522%257D%252C%2522clrgqbw6r0006356gxympnsru%2522%253A%257B%2522id%2522%253A%2522clrgqbw6r0006356gxympnsru%2522%252C%2522activeTabId%2522%253A%2522clrgqj5tt018c356go9deioxr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrgqbw6r0005356gyp4kljup%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrgqj5tt018c356go9deioxr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrgqbw6r0004356g8twxvc3w%2522%253A%257B%2522id%2522%253A%2522clrgqbw6r0004356g8twxvc3w%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clrgqrfyz02iy356gseyuxze9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrgqrfyz02iy356gseyuxze9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

to reproduce, run a build of the server `npm run build` (you will see a console log of the #000000 color too) and then start it

**Comment by scttcper** [comment]
thats really weird

**Comment by michaellocher** [comment]
hey @scttcper seems that the concatenate matcher regex seems to have an issue if you'll use templated strings. i faced the same problem using parcel…

**Comment by Specy** [comment]
I'm also gonna try to investigate later where this problem might be coming from, haven't had the time to yesterday

**Comment by scttcper** [comment]
yeah i'd assume the problem is somewhere in `format-input.ts`  probably a regex like @michaellocher says in the stringInputToObject function. maybe swc is breaking them? I think both of those bundlers use swc where the demo website is using esbuild in production

**Comment by michaellocher** [comment]
See https://github.com/scttcper/tinycolor/pull/249

**Comment by scttcper** [comment]
tried out [4.0.3](https://github.com/scttcper/tinycolor/releases/tag/v4.0.3) and it looks like its working

**Comment by michaellocher** [comment]
Very good, i've tried it this afternoon as well and seems to be ok. Maybe we should check the possible issue with swc, and field an issue.
